### ISSUE TITLE
[FEATURE] Implement New and Improved Approach

### ISSUE THREAD

**Issue by muelitas** [muelitas/stockAnalyzer#12]
## Description
Instead of having three different programs (downloader, updater and analyzer), we are putting merging downloader and updater.
We are also changing the context of analyzer a little since updater will be doing some analysis of stocks ahead of time and store the results. This way, when analyzer runs, the overhead of its operations is minimal (it can focus merely on gathering current stocks' prices and just comparing against previously stored analysis).

## Tasks
- [ ] All services in utils, move them to the root folder; remove utils folder
- [ ] downloader, updater and analyzer will also leave in the root folder; they will share the validator, logger, color_printer and any additional services (i.e. emailer)
- [ ] Don't forget that at some point, today's stock list needs to be stored so that it can be compared against tomorrow (and if some stocks are no longer in list, to remove hData, metrics, etc.)

## Diagrams
![Stock Analyzer Flow Diagram 1](https://github.com/muelitas/stockAnalyzer/assets/64393629/2e75aab0-66c4-4ae1-a715-603a9f721536)

![Stock Analyzer Flow Diagram 2](https://github.com/muelitas/stockAnalyzer/assets/64393629/c826f9ff-61f5-431d-bde8-7ca5e5dcafe3)
