### ISSUE TITLE
[FEATURE] Downloader - Configuration file and parsed flags

### ISSUE THREAD

**Issue by muelitas** [muelitas/stockAnalyzer#2]
## Tasks
- [x] Downloader will receive configuration file that includes the following values:
    - [x] `years`: the number of years of historical data to be downloaded
    - [x] `download_dir`: path to directory where historical data will be saved
    - [x] `symbols`: stocks' symbols for which historical data will be downloaded
- [x] Ensure cli options/flags can be parsed onto downloader:
    - [x] Include a `--config` flag; this will be the path to the configuration file
