### ISSUE TITLE
[FEATURE] Downloader - Validate Given Paths

### ISSUE THREAD

**Issue by muelitas** [muelitas/stockAnalyzer#4]
### Tasks
- [x] Validate path to configuration file
- [x] Validate path to `download_dir`
- [x] Implement colorful error/warning messages
