### ISSUE TITLE
[FEATURE] Downloader - Download and save functionality

### ISSUE THREAD

**Issue by muelitas** [muelitas/stockAnalyzer#7]
## Tasks
- [ ] Implement download functionality:
    - [ ] Use _queues_ as the data structure in which historical data will be saved
    - [ ] Save historical data of all symbols in a pickle file
